# Настройки плагина HFactionss v2.0
settings:
  faction:
    max-name-length: 16
    min-name-length: 3
    disallowed-name-chars: "[^a-zA-Z0-9_]" # Регулярное выражение для недопустимых символов
    max-members: 20 # Максимальное количество участников (включая лидера и офицеров)
  invite:
    timeout-seconds: 120 # Время действия приглашения в секундах

messages:
  prefix: "&e[HFactions] &r"
  reload: "&aКонфигурация HFactionss перезагружена."
  player-only: "&cЭту команду может использовать только игрок."
  no-permission: "&cУ вас нет прав для выполнения этого действия ({permission})."
  faction-not-found: "&cФракция '{argument}' не найдена."
  player-not-found: "&cИгрок '{argument}' не найден или не в сети."
  faction-command-usage: "&cИспользование: /f {subcommand} {usage}"
  help:
    header: "&6--- Помощь по HFactionss ---"
    format: "&e/f {command} {args} &7- {description}"
    # Добавь сюда описания для всех команд
    create: "create <название> - Создать фракцию"
    disband: "disband - Распустить вашу фракцию (лидер)"
    invite: "invite <игрок> - Пригласить игрока (лидер/офицер)"
    join: "join <название> - Принять приглашение во фракцию"
    leave: "leave - Покинуть текущую фракцию"
    kick: "kick <игрок> - Исключить игрока (лидер/офицер)"
    promote: "promote <игрок> - Повысить участника до офицера (лидер)"
    demote: "demote <игрок> - Понизить офицера до участника (лидер)"
    show: "show [название] - Показать информацию о фракции"
    list: "list - Показать список фракций"
    reload: "reload - Перезагрузить конфиг (hfactionss.admin)"

  create:
    success: "&aФракция '&f{faction_name}&a' успешно создана!"
    fail-exists: "&cФракция с таким именем уже существует."
    fail-in-faction: "&cВы уже состоите во фракции."
    fail-name-length: "&cНазвание фракции должно быть от {min} до {max} символов."
    fail-name-chars: "&cНазвание фракции содержит недопустимые символы."
    usage: "create <название>"

  disband:
    confirm: "&cВы уверены, что хотите распустить фракцию? Это действие необратимо. Введите /f disband confirm для подтверждения."
    success: "&aВаша фракция '{faction_name}' была распущена."
    fail-not-leader: "&cТолько лидер может распустить фракцию."
    fail-not-in-faction: "&cВы не состоите во фракции."
    usage: "disband [confirm]"

  invite:
    success-sent: "&aПриглашение во фракцию '{faction_name}' отправлено игроку {player_name}."
    success-received: "&aВы были приглашены во фракцию '{faction_name}' лидером {inviter_name}. Используйте &e/f join {faction_name}&a для вступления в течение {timeout} секунд."
    fail-no-permission: "&cТолько лидер или офицеры могут приглашать игроков."
    fail-player-in-faction: "&cИгрок {player_name} уже состоит в фракции."
    fail-faction-full: "&cВаша фракция достигла лимита участников ({max_members})."
    fail-already-invited: "&cИгрок {player_name} уже приглашен в вашу фракцию."
    fail-invite-self: "&cВы не можете пригласить самого себя."
    fail-not-in-faction: "&cВы должны быть во фракции, чтобы приглашать."
    usage: "invite <игрок>"

  join:
    success: "&aВы успешно вступили во фракцию '{faction_name}'!"
    broadcast: "&aИгрок {player_name} вступил во фракцию."
    fail-no-invite: "&cУ вас нет приглашения во фракцию '{faction_name}' или оно истекло."
    fail-already-in-faction: "&cВы уже состоите в другой фракции. Покиньте ее (/f leave), чтобы вступить в новую."
    fail-faction-full: "&cФракция '{faction_name}' заполнена."
    usage: "join <название_фракции>"

  leave:
    success: "&aВы покинули фракцию '{faction_name}'."
    broadcast: "&cИгрок {player_name} покинул фракцию."
    fail-leader: "&cЛидер не может покинуть фракцию. Распустите ее (/f disband) или передайте лидерство (/f setleader <игрок> - нужно реализовать)."
    fail-not-in-faction: "&cВы не состоите во фракции."
    usage: "leave"

  kick:
    success: "&aИгрок {target_name} был исключен из фракции."
    success-target: "&cВы были исключены из фракции '{faction_name}' игроком {kicker_name}."
    fail-no-permission: "&cТолько лидер или офицеры могут исключать игроков."
    fail-cannot-kick-leader: "&cНельзя исключить лидера фракции."
    fail-cannot-kick-officer: "&cОфицер не может исключить другого офицера (только лидер)."
    fail-cannot-kick-self: "&cВы не можете исключить себя."
    fail-target-not-in-faction: "&cИгрок {target_name} не состоит в вашей фракции."
    fail-not-in-faction: "&cВы не состоите во фракции."
    usage: "kick <игрок>"

  promote:
    success: "&aИгрок {target_name} повышен до Офицера."
    success-target: "&aВы были повышены до Офицера во фракции '{faction_name}'."
    fail-not-leader: "&cТолько лидер может повышать участников."
    fail-target-not-member: "&cИгрок {target_name} не является обычным участником вашей фракции."
    fail-target-already-officer: "&cИгрок {target_name} уже является офицером."
    fail-promote-self: "&cВы не можете повысить себя."
    fail-not-in-faction: "&cВы не состоите во фракции."
    usage: "promote <игрок>"

  demote:
    success: "&aИгрок {target_name} понижен до Участника."
    success-target: "&cВы были понижены до Участника во фракции '{faction_name}'."
    fail-not-leader: "&cТолько лидер может понижать офицеров."
    fail-target-not-officer: "&cИгрок {target_name} не является офицером вашей фракции."
    fail-demote-self: "&cВы не можете понизить себя."
    fail-not-in-faction: "&cВы не состоите во фракции."
    usage: "demote <игрок>"

  show:
    header: "&6--- Фракция: &f{faction_name} &6---"
    leader: "&cЛидер: &f{leader_name}"
    officers: "&eОфицеры ({count}): &f{officer_list}"
    members: "&aУчастники ({count}): &f{member_list}"
    no-officers: "&eОфицеры ({count}): &7Нет"
    no-members: "&aУчастники ({count}): &7Нет"
    total: "&bВсего: &f{total_members}/{max_members}"
    not-in-faction: "&cВы не состоите во фракции, укажите название: /f show <название>"

  list:
    header: "&6--- Список фракций ({count}) ---"
    format: "&f{faction_name} &7({online_count}/{total_count} онлайн)"
    empty: "&7На сервере пока нет фракций."