name: HFactionss
version: 2.0 # Обновленная версия
main: org.isyateq.hfactions.HFactions
api-version: 1.21.3 # Используем актуальную версию API
author: IsyaTeq
description:

commands:
  f:
    description: Основная команда фракций.
    usage: /f help
    aliases: [faction, factions]

permissions:
  hfactionss.admin:
    description: Доступ ко всем командам фракций (для админов).
    default: op
  hfactionss.use:
    description: Разрешает использование базовых команд фракций (help, show, list).
    default: true
  hfactionss.create:
    description: Разрешает создание фракции.
    default: true
  hfactionss.disband:
    description: Разрешает распускать свою фракцию (только лидер).
    default: true
  hfactionss.invite:
    description: Разрешает приглашать игроков (лидер/офицер).
    default: true
  hfactionss.kick:
    description: Разрешает исключать игроков (лидер/офицер).
    default: true
  hfactionss.promote:
    description: Разрешает повышать игроков (лидер).
    default: true
  hfactionss.demote:
    description: Разрешает понижать игроков (лидер).
    default: true
  hfactionss.join:
    description: Разрешает вступать во фракцию по приглашению.
    default: true
  hfactionss.leave:
    description: Разрешает покидать фракцию.
    default: true
  # Добавь другие пермишены по необходимости